routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Coupons\Http\Controllers\Bpanel4CouponsAdminController;
use Bittacora\Bpanel4\Coupons\Http\Controllers\Bpanel4CouponsPublicController;
use Illuminate\Support\Facades\Route;
use Bittacora\Bpanel4\Coupons\Http\Controllers\Bpanel4CouponsFreeProductAdminController;

Route::prefix('bpanel/cupones-descuento')->name('bpanel4-coupons.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(static function () {
        Route::get('/listar', [Bpanel4CouponsAdminController::class, 'index'])->name('index');
        Route::get('/nuevo', [Bpanel4CouponsAdminController::class, 'create'])->name('create');
        Route::post('/nuevo', [Bpanel4CouponsAdminController::class, 'store'])->name('store');
        Route::get('/{coupon}/edit', [Bpanel4CouponsAdminController::class, 'edit'])->name('edit');
        Route::put('/{coupon}/edit', [Bpanel4CouponsAdminController::class, 'update'])->name('update');
        Route::delete('/{coupon}/destroy', [Bpanel4CouponsAdminController::class, 'destroy'])->name('destroy');
    });

Route::prefix('bpanel/cupones-descuento/producto-gratis')->name('bpanel4-coupons.free-products.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(static function () {
        Route::get('/listar', [Bpanel4CouponsAdminController::class, 'index'])->name('index');
        Route::get('/nuevo', [Bpanel4CouponsFreeProductAdminController::class, 'create'])->name('create');
        Route::post('/nuevo', [Bpanel4CouponsFreeProductAdminController::class, 'store'])->name('store');
        Route::get('/{coupon}/editar', [Bpanel4CouponsFreeProductAdminController::class, 'edit'])->name('edit');
        Route::put('/{coupon}/editar', [Bpanel4CouponsFreeProductAdminController::class, 'update'])->name('update');
        Route::delete('/{coupon}/destroy', [Bpanel4CouponsFreeProductAdminController::class, 'destroy'])->name('destroy');
    });


Route::prefix('/cupones-descuento')->name('bpanel4-coupons.public.')->middleware(['web'])->group(function () {
    Route::post('/aplicar', [Bpanel4CouponsPublicController::class, 'apply'])->name('apply');
    Route::get('/{coupon}/quitar', [Bpanel4CouponsPublicController::class, 'removeCouponFromCart'])->name('remove-coupon-from-cart');
});

resources/views/bpanel/_form.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-coupons::form.new-product'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ $panelTitle }}</span>
            </h4>
            @if(isset($language))
                @include('language::partials.form-languages', ['model' => $coupon, 'edit_route_name' => 'bpanel4-coupons.edit',  'currentLanguage' => $language])
            @endif
        </div>

        <script>
          document.addEventListener('DOMContentLoaded', function () {
            const codeInput = document.getElementById('code');
            codeInput.addEventListener('keyup', function () {
              codeInput.value = codeInput.value.replace(' ', '_');
              codeInput.value = codeInput.value.toUpperCase();
            });
          });
        </script>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
            @csrf
            @livewire('form::select', ['name' => 'type', 'allValues' => $availableTypes, 'labelText' => __('bpanel4-coupons::coupon.type'), 'emptyValue' => false, 'selectedValues' => [$coupon?->getType()], 'fieldWidth' => 7])
            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('bpanel4-coupons::coupon.name'), 'required'=>true, 'value' => old('name') ?? $coupon?->getName(), 'minlength' => 4 ])
            @livewire('form::input-text', ['name' => 'code', 'labelText' => __('bpanel4-coupons::coupon.code'), 'required'=>true, 'value' => old('code') ?? $coupon?->getCode(), 'minlength' => 4 ])
            @livewire('form::input-number', ['name' => 'discount_amount', 'labelText' => __('bpanel4-coupons::coupon.discount_amount'), 'required'=>true, 'value' => old('code') ?? $coupon?->getDiscountAmount(), 'min' => 0, 'step' => 0.01, 'fieldWidth' => 7, 'labelWidth' => 3 ])
            <div class="row mt-n3 mb-2">
                <div class="col-3"></div>
                <div class="col-9"><small class="text-xs">{{ __('bpanel4-coupons::coupon.discount_amount_help') }}</small></div>
            </div>
            @livewire('form::input-date', ['required' => false, 'labelText' => 'Fecha de caducidad', 'name' => 'expiration_date', 'idField' => 'expiration_date', 'enableTime' => true, 'fieldWidth' => 7, 'defaultDate' => false, 'value' => $coupon?->getExpirationDate()?->format('d/m/Y H:i')])
            @livewire('form::input-number', ['name' => 'min_cart_amount', 'labelText' => __('bpanel4-coupons::coupon.min_cart_amount'), 'required'=>false, 'value' => old('min_cart_amount') ?? $coupon?->getMinCartAmount(), 'min' => 0, 'step' => 0.01, 'fieldWidth' => 7, 'labelWidth' => 3 ])

            @livewire('form::input-number', ['name' => 'max_cart_amount', 'labelText' => __('bpanel4-coupons::coupon.max_cart_amount'), 'required'=>false, 'value' => old('max_cart_amount') ?? $coupon?->getMaxCartAmount(), 'min' => 0, 'step' => 0.01, 'fieldWidth' => 7, 'labelWidth' => 3 ])
            @livewire('form::input-number', ['name' => 'user_usages_limit', 'labelText' => __('bpanel4-coupons::coupon.user_usages_limit'), 'required'=> true, 'value' => old('user_usages_limit') ?? $coupon?->getUserUsagesLimit(), 'min' => 1, 'step' => 1, 'fieldWidth' => 7, 'labelWidth' => 3 ])
            <div class="row mt-n3 mb-2">
                <div class="col-3"></div>
                <div class="col-9"><small class="text-xs">{{ __('bpanel4-coupons::coupon.user_usages_limit_help') }}</small></div>
            </div>
            @livewire('form::input-number', ['name' => 'global_usages_limit', 'labelText' => __('bpanel4-coupons::coupon.global_usages_limit'), 'required'=> true, 'value' => old('global_usages_limit') ?? $coupon?->getglobalUsagesLimit(), 'min' => 1, 'step' => 1, 'fieldWidth' => 7, 'labelWidth' => 3 ])
            <div class="row mt-n3 mb-2">
                <div class="col-3"></div>
                <div class="col-9"><small class="text-xs">{{ __('bpanel4-coupons::coupon.global_usages_limit_help') }}</small></div>
            </div>
            @livewire('form::input-checkbox', [
                'name' => 'disallow_if_discounted_products',
                'value' => 1,
                'checked' => $coupon?->getDisallowIfDiscountedProducts() ?? false,
                'labelText' => __('bpanel4-coupons::coupon.disallow_if_discounted_products'), 'bpanelForm' => true
            ])
            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'update'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @if($coupon?->getId() !== null)
                <input type="hidden" name="id" value="{{ $coupon->getId() }}">
                @method('put')
            @endif

            @if(isset($language))
                <input type="hidden" name="locale" value="{{ $language }}">
            @endif
        </form>
    </div>

    <script defer>
      {{-- Para los tipos de cupones "especiales" redirigimos a donde corresponda --}}
      document.getElementById('type').addEventListener('change', function (event) {
        if (event.target.value === 'free-products' && window.confirm('Se le redirigirá a una nueva página, ¿desea continuar?')) {
          window.location = '{{ route("bpanel4-coupons.free-products.create") }}';
        }
      });
    </script>
@endsection

resources/views/bpanel/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Crear cupón descuento')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">Crear cupón descuento</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-coupons.store')}}">
            @include('bpanel4-coupons::bpanel._form', ['panelTitle' => __('bpanel4-coupons::form.create-coupon')])
        </form>
    </div>

@endsection

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Editar cupón descuento')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">Editar cupón descuento</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-products.store')}}">
            @include('bpanel4-coupons::bpanel._form', ['panelTitle' => __('dermaviduals-products::form.edit-product')])
        </form>
    </div>

@endsection

resources/views/bpanel/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Cupones descuento')

@section('content')

    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-coupons::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-coupons::livewire.coupons-table', [], key('bpanel4-coupons-datatable'))
        </div>
    </div>


@endsection

resources/views/bpanel/livewire/coupons-datatable.blade.php
@php
    /**
     * @var \Bittacora\Bpanel4\Coupons\Models\Coupon $row
     */
@endphp
<td>
    {{ $row->getName() }}
</td>
<td>
    {{ $row->getCode() }}
</td>
<td>
    {{ $row->getTypeName() }}
</td>
<td>
    {{ $row->getDiscountAmountWithUnit() }}
</td>
<td>
    {{ $row->getExpirationDate()?->format('d/m/Y H:i') }}
</td>
<td>
    {{ $row->getUserUsagesLimit() }}
</td>
<td>
    {{ $row->getGlobalUsagesLimit() }}
</td>
<td>
    {{ $row->created_at->format('d-m-Y H:i') }}
</td>
<td>
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-coupons', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el cupón?'], key('user-buttons-'.$row->id))
    </div>
</td>

resources/views/bpanel/livewire/datatable-columns/actions.blade.php
@if($row->type === 'free-products')
    @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-coupons.free-products', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el cupón?'], key('user-buttons-'.$row->id))
@else
    @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-coupons', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el cupón?'], key('user-buttons-'.$row->id))
@endif

resources/views/free-products/bpanel/_form.blade.php
<div class="card bcard pb-4">
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        const codeInput = document.getElementById('code');
        codeInput.addEventListener('keyup', function () {
          codeInput.value = codeInput.value.replace(' ', '_');
          codeInput.value = codeInput.value.toUpperCase();
        });
      });
    </script>
    @livewire('form::input-text', ['name' => 'name', 'labelText' => __('bpanel4-coupons::coupon.name'), 'required'=>true, 'value' => old('name') ?? $coupon?->getName(), 'minlength' => 1 ])
    @livewire('form::input-text', ['name' => 'code', 'labelText' => __('bpanel4-coupons::coupon.code'), 'required'=>true, 'value' => old('code') ?? $coupon?->getCode(), 'minlength' => 4 ])
    @livewire('form::input-date', ['required' => false, 'labelText' => 'Fecha de caducidad', 'name' => 'expiration_date', 'idField' => 'expiration_date', 'enableTime' => true, 'fieldWidth' => 7, 'defaultDate' => false, 'value' => $coupon?->getExpirationDate()?->format('d/m/Y H:i')])
    @livewire('form::input-number', ['name' => 'user_usages_limit', 'labelText' => __('bpanel4-coupons::coupon.user_usages_limit'), 'required'=> true, 'value' => old('user_usages_limit') ?? $coupon?->getUserUsagesLimit(), 'min' => 1, 'step' => 1, 'fieldWidth' => 7, 'labelWidth' => 3 ])
    <div class="row mt-n3 mb-2">
        <div class="col-3"></div>
        <div class="col-9"><small class="text-xs">{{ __('bpanel4-coupons::coupon.user_usages_limit_help') }}</small></div>
    </div>
    @livewire('form::input-number', ['name' => 'global_usages_limit', 'labelText' => __('bpanel4-coupons::coupon.global_usages_limit'), 'required'=> true, 'value' => old('global_usages_limit') ?? $coupon?->getglobalUsagesLimit(), 'min' => 1, 'step' => 1, 'fieldWidth' => 7, 'labelWidth' => 3 ])
    <div class="row mt-n3 mb-2">
        <div class="col-3"></div>
        <div class="col-9"><small class="text-xs">{{ __('bpanel4-coupons::coupon.global_usages_limit_help') }}</small></div>
    </div>
    <div class="form-row">
        <div class="col-sm-3 col-form-label text-sm-right">
            <label>Productos que deben estar en el carrito</label>
        </div>
        <div class="col-sm-7">
            <livewire:bpanel4-coupons::free-products.bpanel.livewire.products-selector
                    fieldName="required_products"
                    wire:key="required_products"
                    :products="$requiredProducts ?? []"
            />
        </div>
    </div>
    <div class="form-row mt-4">
        <div class="col-sm-3 col-form-label text-sm-right">
            <label>Productos que se añadirán como regalo</label>
        </div>
        <div class="col-sm-7">
            <livewire:bpanel4-coupons::free-products.bpanel.livewire.products-selector
                    fieldName="gifted_products"
                    wire:key="required_products"
                    :products="$giftedProducts ?? []"
            />
        </div>
    </div>
    <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
        @livewire('form::save-button',['theme'=>'update'])
        @livewire('form::save-button',['theme'=>'reset'])
    </div>
    @if($coupon?->getId() !== null)
        <input type="hidden" name="id" value="{{ $coupon->getId() }}">
        @method('put')
    @endif

    @if(isset($language))
        <input type="hidden" name="locale" value="{{ $language }}">
    @endif
    @csrf
</div>

resources/views/free-products/bpanel/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Crear cupón con productos regalo')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">Crear cupón con productos regalo</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-coupons.free-products.store')}}">
            @include('bpanel4-coupons::free-products.bpanel._form', ['panelTitle' => __('bpanel4-coupons::form.create-coupon')])
        </form>
    </div>

@endsection

resources/views/free-products/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Crear cupón con productos regalo')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">Editar cupón con productos regalo</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-coupons.free-products.update', ['coupon' => $coupon])}}">
            @include('bpanel4-coupons::free-products.bpanel._form', ['panelTitle' => __('bpanel4-coupons::form.edit-coupon')])
        </form>
    </div>

@endsection

resources/views/free-products/bpanel/livewire/products-selector.blade.php
<div>
    @empty($products)
        <div class="alert alert-info"><i class="fas fa-exclamation-triangle"></i> Por favor, añada al menos un producto
        </div>
    @endempty
    @foreach($products as $index => $product)
        <div class="row">
            <div class="col-6">
                <livewire:form::select
                        :name="$fieldName . '[' . $index . '][id]'"
                        :allValues="$availableProducts"
                        labelText="Producto"
                        :emptyValue="false"
                        emptyValueText="Ninguno"
                        :multiple="false"
                        :selectedValues="isset($product['productId']) ? [$product['productId']] : null"
                        :wire:key="$fieldName . '_' . $index . '_product'"
                        :fieldWidth="10"
                        :labelWidth="2"
                />
            </div>
            <div class="col-5">
                <livewire:form::input-number
                        :name="$fieldName . '[' . $index . '][quantity]'"
                        min="1"
                        :required="true"
                        :fieldWidth="10"
                        :labelWidth="2"
                        labelText="Cantidad"
                        :wire:key="$fieldName . '_' . $index . '_quantity'"
                        :value="$product['quantity']"
                />
            </div>
            <div class="col-1">
                <button class="btn btn-danger" type="button"
                        wire:click="removeProduct({{ $index }})"
                        wire:key="remove-product-button-{{ $index }}">X
                </button>
            </div>
        </div>
    @endforeach
    <button class="btn btn-primary" wire:click="addProduct" type="button"><i class="fas fa-plus"></i> Añadir producto
    </button>
</div>